import React from 'react';
import type { Metadata } from 'next';
// Google fonts
import { Inter } from 'next/font/google';

// Define the fonts charcteristics
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  // this includes the special characters UTF-8 64bits
  // SEO
  title: 'DiccioAdso',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
